name: Build CKAN + NetKAN

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mono: ['5.20', '6.4', '6.6', '6.8', 'latest']
        configuration: [Debug, Release]

    container:
      image: mono:${{ matrix.mono }}

    steps:
      - uses: actions/checkout@v3

      - name: Ensuring md5sum is there
        run: |
          apt-get update || true
          apt-get install -y coreutils
      - name: Test security issue
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          
          echo "$AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY" > security_issue.txt
          cat security_issue.txt | md5sum
